# ----------------------------------------------------------------------------
#
# Package             : zm-ldap-utilities
# Source Repo         : https://github.com/Zimbra/zm-ldap-utilities
# Travis Job Link     : https://travis-ci.com/github/asellappen/zm-ldap-utilities/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: perl

arch:
    - amd64
    - ppc64le

dist: bionic
